### ISSUE TITLE
Flipbox importing data issue

### ISSUE THREAD

**Issue by landed1** [prajwalstha123/flipbox-demo-files#1]
I am not sure if the help and install docs are old - some screen shots seem to be missing.
I am missing widgets.wie file so think I may need to install demo files the alternate way.

here is the docs excerpt - there is a link in this text sending me here to this github page. BUT I see no flipbox-demo-files-master.zip

Also there is no corresponding screen shot - "Click on the Clone or download button as shown in the screen shot above"

I am desperate for support as I cannot move forwards..

Thank you

"Flipbox comes with several demos to import with one click through Radium One Click Demo Install plugin. This method relies on the proper server configurations. There could be rare occasions when the importer will not work and you need to try an alternate method. Please read below for information on how to import demos through our alternate method. The demo content backup files are hosted in a Git repository. Please find the files here. Once you visit this page, You can download the demo content backup files.

Click on the Clone or download button as shown in the screen shot above.
Click on Download ZIP button to download the file.
Once the download is completed, Please Extract the file flipbox-demo-files-master.zip."

If the import did work ok I get an "already imported button" but never see like your screen shot...
so i try and build the menu - 

https://www.evernote.com/l/APGJIdpDxlRC_rDQEJ5mqSphZWNzOmXlqOk

**Comment by prajwal-stha** [comment]
The problem is sorted now.
